language: rust
rust:
- '1.25.0'
cache: cargo
script:
- cargo build --release
- docker login -p "$DOCKER_PASSWORD" -u "$DOCKER_LOGIN" 
- docker build -t loadapi_server:dev .
- docker tag loadapi_server:dev docker.io/nmasse/loadapi_server:dev
- docker push docker.io/nmasse/loadapi_server:dev
env:
  global:
    secure: "Hm+jJGJ3hdbXYdBn/gQUlUrvsRiWwycilS+CIihgfJI9RjvqhCGSGl0C2s/8QJXx0YFeI5c+JcpJYyx9hewqRRuWvVmutJZM12+JJqr6cF/XIXS68g1EnhOW3RG07KBm2nVVSUUzHK41U9mDEvinwRw6cpDukB/rtjq77iuYj/NV9V6YZpBCK/eS4tUDCYSw3mmkNksHdhU+vQ7npsgqSfd17EEbzs4kx6g9VyX3b4OIieQkelyc44oj2rYvZ29VwdpZHDCp606eL5AEJw6XJPJfkDh6zd1WPVEeBaQcYx9FL+wpV9+M6PN3FDByibEfwvGLxUTLz4RHgsobRKcrVdcnAg8tZziUUGyNLjJtsks+TfZNIJjjvrk5a052MP8pzF2tcKUZLDW01C2RSPSVqqvhoFFxHPZRjCSwYMAAcCrvwS8BOCpCStfVtBQ8b03w6MUuUDIQIHD+UBHtssvgkf0EcfsSMh+zuSfUvc8fK/CQHYtrnnU7QXO7T1LBXmHD/weprE16/f/pbRnvfMz9ZfNRTtW2kz/wAyQ3wTbwPHsRQCYJQzc/PXvIDlIQEQpOYFZTc/91Fs54vSHdxlYRVMkAExU/TccCLrGVmj4GiULpry4woAqaDNp0W0Fr0P3FxlNyqiOji4vahOVNFykSJqawwpVyRzueBv2HrGwKbLs="
services:
  - docker
